### ISSUE TITLE
Feature request: control vertical or horizontal display

### ISSUE THREAD

**Issue by jwpease** [stefanomarra/jquery-roadmap#1]
I found your great timeline, and it looks great, and is very easy to use.   I would like to make a feature request... Can you add an option to control horizontal or vertical display?  I love how responsive it is, and on smaller screens the vertical looks great, but I am having an issue when I want to show the timeline in a vertical position by default.

Thank you! 
Jeremy.

**Comment by stefanomarra** [comment]
Hi Jeremy, thanks a lot!
Seems a nice feature.
How would you call this option? Maybe `direction`?

**Comment by jwpease** [comment]
Thanks Stefano.  I think "orientation" might be better.

  Thanks again!

  Jeremy.

**Comment by stefanomarra** [comment]
@jwpease just added `orientation` option to v1.3.0.

Here's an example to force the timeline only to vertical:
```
$("#my-roadmap").roadmap(data, {
	eventsPerSlide: 4,
	slide: 1,
	rootClass: 'roadmap',
	orientation: 'vertical'
});
```

Should work as expected ;)

**Comment by stefanomarra** [comment]
Closing this issue.

Feel free to open it again if needed.
