### ISSUE TITLE
Not shown in the right place

### ISSUE THREAD

**Issue by amberhpp** [stefanomarra/jquery-roadmap#2]
Please forgive me for my poor English.
it's not shown in the right place.Can you give me some useful suggestion？
![default](https://user-images.githubusercontent.com/40970184/53398365-66b55f80-39e4-11e9-97a1-0354954645f1.PNG)
Thank you very much.

**Comment by DanielMunch** [comment]
Has this bug been fixed yet @stefanomarra ? I have the same problem at the moment.

**Comment by DanielMunch** [comment]
@stefanomarra I found the bug. You just have to add this line under the responsive @media part of the css.

.roadmap.roadmap--orientation-auto .roadmap__events__event:nth-child(odd) .event {
		top: -10px
	}

**Comment by stefanomarra** [comment]
Hi guys, I just pushed v1.3.2 that fixes the issue.
It should work as expected now ;)
