### ISSUE TITLE
Create onBuild Event in options

### ISSUE THREAD

**Issue by ivan-technocrat** [stefanomarra/jquery-roadmap#4]
Hi,
I couldn't find any events in options, so I added own onBuild event. I tried to push a new branch for creating PR, but I don't have permission to create a branch on the repository.
The patch is in the next comment.

Here is an example of using:
`      $('#timeline').roadmap(events, {
        eventsPerSlide: 6,
        slide: 1,
        prevArrow: '<i class="material-icons">keyboard_arrow_left</i>',
        nextArrow: '<i class="material-icons">keyboard_arrow_right</i>',
        onBuild: function() {

        }
      });`

**Comment by ivan-technocrat** [comment]
[add-onBuild-patch.txt](https://github.com/stefanomarra/jquery-roadmap/files/3230953/add-onBuild-patch.txt)

**Comment by ivan-technocrat** [comment]
![Screenshot from 2019-05-29 11-55-54](https://user-images.githubusercontent.com/33712192/58533242-c56bbe80-8209-11e9-8caa-05ae3fcf4056.png)

**Comment by stefanomarra** [comment]
Hi @ivan-technocrat I just pushed v1.4.0 with onBuild option
